# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-23 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_auto_20170222_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='age',
            field=models.IntegerField(default=19, verbose_name='\u5e74\u9f84'),
        ),
    ]
